swagger: "2.0"
servers:
  - description: SwaggerHub API
    url: HTTP
  - description: SwaggerHub API
    url: HTTPS
info:
  description: This is a Library API
  version: 1.0.0
  title: Library API
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

tags:
  - name: "books"
    description: "All the books in this library"
  - name: "users"
    description: "Operations about the people who borrow the books"
  - name: "authors"
    description: "All the people who wrote the books in the library"

paths:
  /books:
    $ref: "./components/books/books.yaml"
  /books/findByISBN/{isbn}:
    $ref: "./components/books/findByISBN.yaml"
  /books/findByTitle/{title}:
    $ref: "./components/books/findByTitle.yaml"
  /books/onloan:
    $ref: "./components/books/onloan.yaml"
  /books/categories/{category}:
    $ref: "./components/books/categories.yaml"
  /users:
    $ref: "./components/users/users.yaml"
  /users/createWithArray:
    $ref: "./components/users/createWithArray.yaml"
  /users/createWithList:
    $ref: "./components/users/createWithList.yaml"
  /users/login:
    $ref: "./components/users/login.yaml"      
  /users/logout:
    $ref: "./components/users/logout.yaml"
  /users/{username}:
    $ref: "./components/users/findByUsername.yaml"
  /authors:
    $ref: "./components/authors/authors.yaml"
  /authors/{authorId}:
    $ref: "./components/authors/singleAuthor.yaml"
  /authors/{authorId}/books:
    $ref: "./components/authors/getAllBooksByAuthor.yaml"

definitions:
  Book:
    $ref: "./components/schemas/BooksSchema.yaml"
  User:
    $ref: "./components/schemas/UsersSchema.yaml"
  Author:
    $ref: "./components/schemas/AuthorsSchema.yaml"
securityDefinitions:
  $ref: "./components/schemas/SecuritySchema.yaml"