swagger: "2.0"
servers:
  - description: SwaggerHub API
    url: HTTP
  - description: SwaggerHub API
    url: HTTPS
info:
  description: This is a Library API
  version: 1.0.0
  title: Library API
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

tags:
  - name: "books"
    description: "All the books in this library"
  - name: "users"
    description: "Operations about the people who borrow the books"
  - name: "authors"
    description: "All the people who wrote the books in the library"

paths:
  /books:
    $ref: "./components/books/books.yaml"
  /books/:isbn: 
    $ref: "./components/books/updateBook.yaml"
  /books/getbyId/:bookId:
    $ref: "./components/books/getById.yaml"
  /books/getbyISBN/:isbn:
    $ref: "./components/books/getByISBN.yaml"
  /books/getByTitle/:title:
    $ref: "./components/books/getByTitle.yaml"
  /books/deleteCopy/:bookId:
    $ref: "./components/books/deleteCopy.yaml"
  /books/deleteBook/:isbn:
    $ref: "./components/books/deleteBook.yaml"
  /books/onloan:
    $ref: "./components/books/onloan.yaml"
  /books/categories:
    $ref: "./components/books/categories.yaml"
  /books/categories/:category:
    $ref: "./components/books/category.yaml"
  
  /users:
    $ref: "./components/users/users.yaml"
  /users/:userId:
    $ref: "./components/users/byUserId.yaml"
  /users/:userId/addtobasket:
    $ref:"/components/users/addToBasket.yaml"
  /users/:userId/removefrombasket:
    $ref:"/components/users/removeFromBasket.yaml"
  /users/:userId/viewbasket:
    $ref:"/components/users/viewBasket.yaml"
  /users/:userId/checkout:
    $ref:"/components/users/checkout.yaml"
  /users/:userId/viewloans:
    $ref:"/components/users/viewLoans.yaml"
  /users/:userId/returnbook:
    $ref:"/components/users/returnBook.yaml"
  /users/:email:
    $ref: "./components/users/byEmail.yaml"
  /users/login:
    $ref: "./components/users/login.yaml"

  
  /authors:
    $ref: "./components/authors/authors.yaml"
  /authors/:authorId:
    $ref: "./components/authors/singleAuthor.yaml"
  /authors/{authorId}/books:
    $ref: "./components/authors/getAllBooksByAuthor.yaml"

definitions:
  Book:
    $ref: "./components/schemas/BooksSchema.yaml"
  User:
    $ref: "./components/schemas/UsersSchema.yaml"
  Author:
    $ref: "./components/schemas/AuthorsSchema.yaml"
securityDefinitions:
  $ref: "./components/schemas/SecuritySchema.yaml"